
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scoring_db
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
      ##- pgdata:/var/lib/postgresql/data
    restart: unless-stopped

#volumes:
  #pgdata:
